class ValidationError(Exception):
    """Исключение вызывается, если данные не прошли валидацию."""
